Repository fga-eps-mds/2023.1-Moody, pull requests merged in 2023-07, with the labels that each got.

#49 organização e verificação
  plugin/lib.php
Labels: enhancement

#62 Transferência e Conexão dos dados no BD
  plugin/lib.php
Labels: bug, Backend, arquivo

#72 Adaptação do codigo
  plugin/db/install.xml
  plugin/lib.php
  plugin/styles.css
  plugin/templates/frontpage.php
  plugin/templates/page.mustache
  plugin/version.php
Labels: Frontend, Backend, arquivo
