Repository fga-eps-mds/2023.1-Moody, pull requests merged in 2023-06, with the labels that each got.

#31 Codigo para o botão do moody
  README.md
  plugin/db/install.php
  plugin/lib.php
Labels: Frontend

#32 desenvolvimento funcional do contador de acesso a turma
  plugin/db/install.php
  plugin/db/install.xml
  plugin/lib.php
  plugin/templates/index.mustache
Labels: enhancement, Backend

#39 contador do tempo de acesso
  plugin/db/install.xml
  plugin/lib.php
Labels: enhancement
